In [59]:
import pandas as pd
import numpy as np

In [13]:
# Dataframe
df = pd.DataFrame(np.arange(0,20).reshape(5,4), index = ['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns = ["Column1", "Column2", "Column3", "Column4"])

In [10]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [11]:
df.to_csv('Test.csv')

In [15]:
#Accessing elements
#using .loc --> location or .iloc --> index location
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [16]:
type(df.loc['Row1'])  #data-series

pandas.core.series.Series

In [17]:
#Take element 3 row 2 column
df.iloc[0:3,0:2]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9

In [18]:
#Take the elements from the column2
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [22]:
#Convert Datframes to array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [23]:
df.iloc[:,1:].values.shape

(5, 3)

In [30]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [32]:
df['Column1'].value_counts()

0     1
8     1
4     1
16    1
12    1
Name: Column1, dtype: int64

In [33]:
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [37]:
df = pd.read_csv('cities.csv')

In [39]:
df.head()

LatD   "LatM"   "LatS"  "NS"   "LonD"   "LonM"   "LonS"  "EW"  \
0    41        5       59   "N"       80       39        0   "W"   
1    42       52       48   "N"       97       23       23   "W"   
2    46       35       59   "N"      120       30       36   "W"   
3    42       16       12   "N"       71       48        0   "W"   
4    43       37       48   "N"       89       46       11   "W"   

               "City"  "State"  
0        "Youngstown"       OH  
1           "Yankton"       SD  
2            "Yakima"       WA  
3         "Worcester"       MA  
4   "Wisconsin Dells"       WI

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   LatD      128 non-null    int64 
 1    "LatM"   128 non-null    int64 
 2    "LatS"   128 non-null    int64 
 3    "NS"     128 non-null    object
 4    "LonD"   128 non-null    int64 
 5    "LonM"   128 non-null    int64 
 6    "LonS"   128 non-null    int64 
 7    "EW"     128 non-null    object
 8    "City"   128 non-null    object
 9    "State"  128 non-null    object
dtypes: int64(6), object(4)
memory usage: 10.1+ KB


In [41]:
df.describe()

LatD      "LatM"      "LatS"      "LonD"      "LonM"      "LonS"
count  128.000000  128.000000  128.000000  128.000000  128.000000  128.000000
mean    38.820312   30.765625   27.492188   93.250000   27.742188   26.960938
std      5.200596   16.426158   18.977814   15.466499   16.927937   18.727807
min     26.000000    1.000000    0.000000   71.000000    0.000000    0.000000
25%     35.000000   16.000000   11.000000   80.000000   14.000000   11.000000
50%     39.000000   31.000000   24.000000   89.500000   26.500000   23.500000
75%     42.250000   45.000000   47.000000  103.250000   40.250000   47.000000
max     50.000000   59.000000   59.000000  123.000000   58.000000   59.000000

In [43]:
df['LatD'].value_counts()

41    12
38    11
39    10
42    10
44     9
43     9
37     9
32     8
40     8
33     7
34     4
46     4
47     4
35     3
36     3
31     3
27     2
30     2
29     2
49     2
45     2
48     1
26     1
28     1
50     1
Name: LatD, dtype: int64

In [44]:
#Get unique category counts
df['LatD'].unique()

array([41, 42, 46, 43, 36, 49, 39, 34, 48, 37, 33, 40, 26, 47, 31, 44, 38,
       28, 32, 30, 27, 35, 29, 45, 50], dtype=int64)

In [75]:
from io import StringIO, BytesIO

In [60]:
data = ('col1, col2, col3\n'
              'x, y, 1\n'
              'a, b, 2\n'
              'c, d, 3')

In [61]:
type(data)

str

In [62]:
StringIO()

In [65]:
pd.read_csv(StringIO(data))

col1  col2   col3
0    x     y      1
1    a     b      2
2    c     d      3

In [86]:
# Read from specific columns

df = pd.read_csv(StringIO(data),usecols=[0,2])


In [87]:
df


col1   col3
0    x      1
1    a      2
2    c      3

In [88]:
df.to_csv('Test1.csv')

In [91]:
df = pd.read_csv('Test1.csv')

In [92]:
df

Unnamed: 0 col1   col3
0           0    x      1
1           1    a      2
2           2    c      3

In [93]:
#Specifying columns data types
data= ('a,b,c,d\n'
          '1,2,3,4\n'
          '5,6,7,8\n'
          '9,10,11,12')

In [95]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12


In [97]:
#Specifing datatype object
df = pd.read_csv(StringIO(data), dtype=object)

In [98]:
df

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [99]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [100]:
#Specifing datatype float
df = pd.read_csv(StringIO(data), dtype=float)

In [101]:
df

a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [102]:
df['a']

0    1.0
1    5.0
2    9.0
Name: a, dtype: float64

In [103]:
df.dtypes

a    float64
b    float64
c    float64
d    float64
dtype: object

In [104]:
#Specifing datatype
df = pd.read_csv(StringIO(data), dtype={'b':int,'c':float,'a':'Int64'})

In [105]:
df

a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [106]:
df.dtypes

a      Int64
b      int32
c    float64
d      int64
dtype: object

In [107]:
data = ('index,a,b,c\n'
          '4,apple,cat,7.2\n'
          '7,banana, dog,10')

In [108]:
#Give indexing with specific
pd.read_csv(StringIO(data),index_col=0)

a     b     c
index                    
4       apple   cat   7.2
7      banana   dog  10.0

In [116]:
data = ('a,b,c\n'
          '4,apple,cat,\n'
          '7,banana, dog,')

In [117]:
pd.read_csv(StringIO(data))

a     b   c
4   apple   cat NaN
7  banana   dog NaN

In [119]:
pd.read_csv(StringIO(data),index_col=False)

a       b     c
0  4   apple   cat
1  7  banana   dog

In [120]:
#Combining usecols and index_col
data = ('a,b,c\n'
          '4,apple,cat,\n'
          '7,banana, dog,')

In [122]:
pd.read_csv(StringIO(data),usecols = ['b', 'c'], index_col=False)

b     c
0   apple   cat
1  banana   dog

In [123]:
#Quoting and escaping characters
data = 'a,b\n"hello, \\"Vipul\\", nice to see you",7'

In [124]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello, "Vipul", nice to see you  7

In [128]:
df = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item', sep='\t')

In [129]:
df.head()

item_code                                          item_name  display_level  \
0       AA0                               All items - old base              0   
1      AA0R  Purchasing power of the consumer dollar - old ...              0   
2       SA0                                          All items              0   
3      SA0E                                             Energy              1   
4     SA0L1                                All items less food              1   

  selectable  sort_sequence  
0          T              2  
1          T            400  
2          T              1  
3          T            375  
4          T            359

#Read Json to CSV